### ISSUE TITLE
Private server incorrect password

### ISSUE THREAD

**Issue by WhiteHalmos** [screepers/python-screeps#13]
I get this response for many api calls: OrderedDict([(u'error', u'incorrect server password')])

Is this because my server has a password? Not sure where to add support for server passwords in the api.

**Comment by tedivm** [comment]
Did you add one of the authentication modules to your private server? You have to add one of them and set a password before the API will work.

**Comment by WhiteHalmos** [comment]
I added screepsmod-auth and set a password. I can call a couple api methods no problem, then I get this error and have to re-authenticate/create the api object.
