### ISSUE TITLE
Is there a endpoint for getting structures, creeps, ... in a room ?

### ISSUE THREAD

**Issue by benjaminderei** [screepers/python-screeps#3]
all is in the title  :)

**Comment by daboross** [comment]
I haven't used this project much, but I'm pretty sure that to get the structures/creeps/etc you need to connect to screeps using websockets - I don't think there's any HTTP endpoint.

**Comment by tedivm** [comment]
Yup- connect to the websocket and subscribe to "rooms". That being said now that the open source server exists we may be able to add better endpoints in for this.
